import React from 'react';


function KeithCyndi() {
    return (
        <div className="container">
            <div className="header-wrapper"><h1>this is KeithCyndi page</h1>
                <div className="Keith-bio">
                    <div className="img-wrapper">
                        <img src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/60501852_2249790898433381_6332161836015681536_n.jpg?_nc_cat=104&_nc_sid=110474&_nc_ohc=EY9NRnUiwn0AX8HrMo0&_nc_ht=scontent-dfw5-2.xx&oh=f4e1effe09c606c58a168bbcdc7ae0b1&oe=5EDBEFFC" alt="img"></img>
                    </div>
                    <p>DOB: 06/10/1960; Parents Larry & Diane Robbins (divorced after 33-years of marriage. Dad married Collen for 10-years before he died last years. Mom died 4-years ago. </p>
                    <p> Age: 59  </p>
                    <p>Religion: LDS, Elder </p>
                    <p>Residences: 3-years in Arizona; 8-years in Seattle, 4-years in Toledo; 2-years Hermiston OR; 3-years Ft Riley KS; 3-years Richland WA; 2-years Kennewick; 3-years Pasco WA; 1-year Olalla WA; Tigard OR 20-years, 1-year Eagle MT UT.  </p>
                    <p>Marriage: Sally-1979-1982; Cyndi 1983-2020-present. Cyndi & I have 8-chidlren, 2-previous marriage, 2- adopted and 4-bioligical: Shanelle, Sterling, Jeremy, Sena, Heith, Casey, Emily and Nathan. Nov 7th Sterling died of OD. Very sad. I miss him. He had so much potential. He was a challenge and a joy. Very funny and very smart, until his peer’s steered him down a dark path he couldn’t stay away from. His bio-si8blings as twins Sterling and Shanelle (adopted) were material twins. Their bio-mother Lisa was permitted to see them, but she was Aunt Lisa. Her eldest 2-daughters are also addicts like mother. Lisa is responsible for her child following in her footsteps. All her friends had OD and now her bio-son, my son at 27. He is missed by entire family. Previously my dad died, recently on Valentines Cyndi’s brother Shane committed suicide by hanging. 2019 was difficult to say the least. She helped raise him. He left behind Isaiah and Orion, 16 and 12. Sad, but the details put blame on Shane wife for pushing to this choice everyone in the family has to live with. Details of his demise must remain personnel. Want them ask Cyndi. </p>
                    <p>Graduated: Hermiston high early to join the military doing the right things. I had won a scholarship in graphics arts but gave it to a girl friends next most deserving. Teacher and Principle permitted and accepted my selection. I finished high school with rarely diploma having all my required credits by February just 2-weeks before Bootcamp. Became best all-around solider in platoon. Marrying girl next door as I got her PG. After being excommunicated I was baptized into the church in 1983 before marrying Cyndi, my greatest decision. I love her still after 37-years. I worry about her. She is sick a lot: malabsorption. I don’t want to be alone.</p>
                    <div className="img-wrapper">
                        <img src="https://scontent-dfw5-1.xx.fbcdn.net/v/t1.0-9/80365033_2683829215029545_7625932957689053184_n.jpg?_nc_cat=111&_nc_sid=110474&_nc_ohc=9Yikf_RZi04AX_M2t2g&_nc_ht=scontent-dfw5-1.xx&oh=52b441ab33369a0af8df838c6230cbdd&oe=5EDD539C" alt="img"></img>
                    </div>
                    <p>Political Affiliation: Republican-Independent-Conservative-Constitutionalist/Federalists.</p>
                    <p>Veteran: 1979-1982-Fort Riley Kansas, Big Red One. Military Policy, 977th MP Company, 112 MP Battalion.</p>
                    <p>Best Sport: Soft ball. Batting average (3rd ward LDS church on 39th and Hawthorne Portland) and Portland City A-league. First place in both. Was best fielder diving on most catches, sliding at base running scoring an average of 6-runs per game. When LDS church focused on serious softball tournaments began with stake championships (2nd) to Regionals (2nd) and then area (2nd). Went to area 3-years in a row: 7th, 5th and 3rd place. Upon my career injury I have not played since 1994. Sad story, but I hold on the good memories. My military soft ball team was very good and we were post champions, 1981.</p>
                    <p>Tour of Duty TDY: Fort Chaffee Arkansas, War Campaign turned, Police actions, turned Humanitarian mission.</p>
                    <p>
                        Many Cuban spend the day boxing. They were very good. Approx. most of the prisoners were gay and displayed their carnal behavior in public. Those having sex in plain view or through windows were arrested. Nearly 25K Refugees came with unknown STD, turned out to be HIVF. Many had full blown AIDS. They were all 
                        
                        dismissed into America before fully treating them, or containing them from the American citizens due to health risks. Half fled to Miami and half to San Francisco bathhouses. There they began spreading AIDS to thousands of Americans. This represents the greatest outbreak of AIDS, thanks to President Carter and Governor Clinton leaving a mess for President Regan to settle. Run the numbers of the blood of Americans on their hands: 25K x 10-Americans infected (sex transference of HIV over 5-years (average life expectancy in 1980s) = 250,000 x 10-Americans infected (sex/blood transference of HIV) over 10-years (average life expectancy due to AIDS cocktail meds) = 2,500,000 American citizens. Now multiply that by over the next 20-years x [(2020) 2,500,000 citizens every year] = 50,000 Americans infected. Most with HIV and now surviving longer because of better meds. The gay population was so debased they were given a street to live among themselves fence away from families. They share 3-wedding dresses for many marriages every day. About 1/3 of the Cubans were good people and spoke some or good English willing to simulated into America. Half became abusers of society as most went on welfare and committed a host of crimes calling for extended family back in Cuba after chain migration. It was legal Cubans who despised their own peoples behaving dishonorably after being welcomed into American where they were treated 100-times better than Cuban dictator permitted.  
                    </p>
                    <p>Personal note: The worst incident as MP was standing guard as first company guarding Cuban Refuges with roped barricades. Over the next 6-months the compound was fenced off with 18’ with 3-rows of constene razor wire. Any way my partner on patrol) covering ¼ of a mile on the north corner entrance to fort ¼ barracks for coming in Refugees on buses, and ¾ open parade field. Many Cubans were out and about after curfew, but we couldn’t do anything about it unless they tried to cross our perimeter. My partner and I could only approach one another keeping 100’ between us. My partner was a black female names Tina. Once Tina and I were at the far end of our beat, 3-cuban males attacked and raped her. One got away as I called for backup and they arrested two males in the act. I was vilified as a white private 3-class, as a racist for not shooting the Cubans and saving Tina. 
                    I felt terrible and the company never let me see her in the hospital. The commander was furious and squared away the entire company. “Private Robbins did the right thing. It was dark and his backstop was not safe as any rounds fired would have like 1: killed Tina or hit innocent Cubans in nearby barracks.” While I was one of the best experts with the M-16, if the targets are all black and the night is pitch black but for porch lights in the distance I couldn’t shoot. If I were 100-feet from her I would have shot and killed all three. The one Cuban who got away took her .45 cal pistol. It was passed around and eventually used to kill a Park Policemen (government patrolman). Tina was taken to the hospital where she had a rape kit and DNC, which failed as she became pregnant assuming she aborted the potentiality. She got out of the Military on a Section-8 (medical discharge). I never knew what happen to her but rumors said she kept the baby as it wasn’t the baby’s fault over the actions of the father. She also gave birth having contracted HIV. 
                    The baby was a curse and a blessing—blessed without HIV, shocking the doctors of the day and family. Tina proved to be a great mother, right from the beginning of her trial. No woman could be asked to do more for their child, however they come into the world. To this day I wonder just how much trouble I would have gotten into if I disobeyed the order to stay apart and I got a clean short at the rapists without hitting my partner or other citizens. Surely my commander would be angry for discharging my weapon as the paper work takes hours with many hours of investigations/interrogations. The growing PC networks would have had a field day…national news. This matter was keep quiet and sweep under the rug. I was counseled very little. Then again if I killed the Cubans, I may have gotten a ribbon, promotion and bonuses for reenlisting. There may have not been any riots seeing what could happen if they committed crimes. All 3-felones were arrested and convicted 
                    of assaulting a military police officer and back to prison they went, for life. In Leavenworth, of which they stayed a short time before a trial, tow were assaulted by other inmates for what they did to a women, spite her being a military police woman. She was Army! God bless her and her little one would be 39-years old today, her mother my age. 
                    </p>
                    <div className="img-wrapper">
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCzPne5eGo6Ed9q4n-leVjd1dxZzvghGupCOBXDQoBbNhnnPLw" alt="img"></img>
                    </div>
                    <p>On a positive note: I arrested the maker of swords. I heard the hammering of metal and investigated. I know the sound of hammer on pipe. In this case bed bunk adapters. Two fused together and flatten and sharpen into swords. I found them in an air-duct vent along with several more. Most swords are found after they are used on another Cuban. While other MP got a metal, I didn’t and I found many more swords and knives then anyone. While I like recognition, in the words of my hero sons (Army) “Dad I know what I did, and God knows and that’s good enough for me!” Right on.</p>
                    <p>Hanford Patrol HPD: I was hired in 1984 and worked as Tactical Response Team members. (TRTM) much like SWAT, or SRT. I wore military camouflage fatigues. I was especially good and staying alive in simulated terrorist attacks. I got hurt jumping an 18’ foot fence. All would be fine but I compensated for my recent left foot injury and put most pressure on the right which I fractured. Didn’t know that until a year later when my foot had a golf ball size bone spire that was surgically removed. I retired just after my 10th year. I was a good host, and better at tactics and 2nd best at running the 700-yard obstacle course and first best on the 50-yards obstacle course. If I wasn’t sick, I could have beaten the 700-yrd course mark at 1.25-minutes. I did 1.35 mins. It was the inverted wall that slowed me some. Very difficult and trying to fix Tigard home sell. Lots of blood sweet and tears-hospital emergency room visits over 20-years.  </p>
                    <p>Eagle Mountain—Newer Home for Cyndi: I have hurt myself (back) in many of my projects. My surgery procedures and implant minimizes my pain so I can do most things but slowly and carefully. I have managed to do half the basement finishing at a cost of 10-K. My tools alone was 2,000. It took me since moving in to get done with the first phase of the permit faking me 8-months (August 2019). I passed inspection first time perfectly April 2020. Because of Cova19 my son Casey couldn’t come down and install bathroom.</p>
                    <p>Nathan: Construction
                    Emily: Nurse ICU, Salt Lake General Hospital      
                    Casey: Plummer
                    Heith: 15-year Chef, turned programmer. 
                    Sena: Phlebotomist. (Vampire) 
                    Jeremy: former phlebotomist with his sister. Currently Dish installer
                    Shanelle: formerly Assisted living for disabled teens and adults. 
                    Sterling: Construction, roofer, Jack of all trades. In heaven his likely building something. </p>
                    <p>Grandchildren— 
                        Brittany 19 (Nathan); Emily 13 (Heith); Lexi 11 (Nathan); Lillie 4 (Jeremy); Twilight 4 (Casey’s dog); Vanessa 3 (Heith); Zachariah 1.2 (Shanelle); Oscar 9 mos (Emily)… 
                    </p>
                    <p>Hobby: Sports viewer, (Blazermaniac) stopped due to COVA19; was a Vail worker in Portland temple 4-years; writing over 30-years (wrote: Bonkers About Butterfly’s, Choices, Crowns of Glory; Viaga Secrets, Cona and Geyr’s & Gibbors. Published Crowns of Glory vol. I—too complicated and no funds to publish vol. II, or sell Vol I. Been working on Geyr’s & Gibbors the last 2.5 years. Hoping to get published for my children sake if not public (LDS audience generally).</p>
                    <p></p>
                    <p></p>
                </div>
            </div>
        </div>
    )
}

export default KeithCyndi;