import React from 'react';


function Sterling() {
    return (
        <div className="container">
            <div className="header-wrapper"><h1>this is Sterling page</h1>
                <div className="Sterling-bio">
                    <div className="img-wrapper">
                <img src="https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/95606492_2980366975375766_3800032500512718848_n.jpg?_nc_cat=104&_nc_sid=8bfeb9&_nc_ohc=I6xq18pb6TgAX8cpG2N&_nc_ht=scontent-dfw5-2.xx&oh=43834267f62b76e9883120ac9c5076d0&oe=5EE5B67C" alt="img"></img>

                <p>Sterling Lewis Robbins: Nicknames: Silver, Sterfri (due to his multi-race mixing with an assortment of character aspects that make a unique persona. From sarcastically serious to funny as hell. </p>
                <p>DOB: 12/5/1991</p>
                <p>DOD:  		Cause of death: DRUG OVERDOSE</p>
                <p>Eulogy of Sterling Lewis Robbins, by his parents Keith & Cyndi Robbins—
                Hello, my name is Kenny, one of Sterling friends: Thank you all for coming to remember Sterling. He was called by Dad:  STER-FRY; for his unique blood-mix, spirit & attitude, lased with humor. Sterling was born in Portland OR OHSU hospital: 12/05/1991. He Passed-on in his tent in downtown Portland under the Burnside Bridge: Friday-11/7/2019, one month short of his 28th Birthday. When you drive over Burnside Bridge you might consider remembering him in a little prayer? He was adopted from kin with his maternal-twin sister, Shanelle Starr Robbins-Healy. They will always be interconnected, like Batman and Robin forever, wherever they are! 
                He was a blessing & a challenge to the Robbins family. He & his sister came to their home with sever medical conditions at 6 months old; including emotional detachment issues: Sterling wanted, deserved & craved attention, as he did throughout his life with good & sad out-comes. Among friends Sterling & Shanelle had many nicknames. For family its: Sterr & Starr. As twins one is white & short, one black & tall. Sterling had the best tan of the Robbins clan. Sterr had his straight & curly hair, while Starr’s hair was very curly to an afro—which Sterr poked fun at. Once Sterling got regular one-on-one attention his smile grew. He was generally smiling, laughing, & cracking jokes, the LIFE of the party. He was a go-go little boy into his adulthood, with sever ADHD issues, emotionally reserved & generally withheld his physical pains inside—building overtime, making him vulnerable. He was often expelled from school, or teachers for rowdiness, causing nurses to call home wondering if Sterr had his meds. He just needed to be exhausted.
                If only he remained sweet & innocent, ever into mischief, seeking something fun every moment. He lived hard in many ways. He was born first, likely kicking his sister back to get out first. Perhaps he knew his time was shorter & had to get started first? If it wasn’t exciting enough he upped-the-anti in both thrill & danger. School wasn’t his forte. He rather figure things out for himself or pick up pointers from Dad or one of his 7-siblings: Nathan, Emily, Casey, Heith, Sena, Jeremy & Shanelle. Together it was a party, ever joking, wrestling while working & playing hard together as well-oiled team most of the time—especially in the season of Whiffle-ball—UNBEATEN! Thanks to both Sterr & Starr scoring often at 3-7 years old, rounding bases like pro’s. Very exciting games. Unknowingly they once played on a water-logged drain-field—septic backed-up. Charlie Brown would have ALSO slide all the way home, like Sterr at four!    
                Sterling loved 7-women. While he was a ladies man, I mean: 1-wife, 1-girlfriend, 3-sisters and 2-Moms. In that vane; the Robbins want to recognize & thank Mom-PHILLIS IZATT, for all her love & caring nature for our Sterling when he left home.   
                Circumstance surrounding his death are sad, but there is a silver-lining. He has many grandparents & extended family members who have recently moved on before him & were likely aiding him in his final hour as they could—waiting for him on the other side of the veil. As for his family, they have faith & hope to see him again. I think it’s the prayer of all of us. He’s in a better place in perfect health surrounded by greater happiness & none of life’s-stresses. Sterling did have a loving heart & his light did shine often. He’d tell Dad he was so awesome & bright he had to wear sun glasses. He makes ANY PAIR Look good! Closest Family & friends will get a pair to wear after services as they wish in reembrace of Sterling. Wear your own pair in remembrance anytime.   
                In closing let me share one of my great MEMORIES with Sterling:</p>
                <p>MY MEMORY OF MY FRIEND STERLING ROBBINS: 
                Beginning at his home with several friends, Sterling was snowboarding off a homemade half-pipe in the front yard. He continued down Village Glenn Drive and all the way to Fanno Creek. That was so cool he insisted we go snowboarding for real. The next morning we hit Hood Mountain—MT Meadows in deep snow. Sterling smartly says, “Let’s hit the biggest run, but he meant it, & off we went with, Sterling going first of course. Down he went for nearly a quarter mile before he lost it, tumbling over & over again. Very funny, but worrisome. It looked nasty, but he bounced up shouting, “LETS KEEP GOING!” We snowboard all day & road home on the bus sleeping all the way, exhausted. Fun times, good memory! He is remembered & loved by family & many friends everywhere. For it is written in our hearts and tagged on a downtown Portland cyclone fence, reading: “RSVP Sterling Robbins.” Love you brother. Amen</p>
                <p>Hello, my name is Bro Neilson. I have been asked to read: ‘Dads 11-memories with his son Sterling L. Robbins—’
                I LOVED STERLING from the day we brought him home. His adoption was a god-send, adding to our four biological children & my eldest two children from precious marriage. I consider myself blessed with a second chance at a big eternal family. That is still possible. Spite our parental failings, it was heart-warming to hear Sterling say, “I have the best parents there is!” Though memories fade thousands remain in thought, written word & heavens record. I remember precious baby & toddler moments—joyful teen-hood to young adult experiences. Sadly it ends there. We may all have wonderful memories of Sterling—simple & great that need not fade away, even in the mist of future trials & tribulations. We are grateful for Sterling 27.9 year life with us, where Sterling shown great potential & love for most everyone he knew. He especially loved Chelsea Bome, Nicole Richie, Kenny Izatt, Matthew Hanson, Andy Dickenson, Tristian Larson & the Sickle brother’s Ryan & Robert.
                Here’s Dad’s 11-Wonderful Memories & Challenges with his awesome Son—
                #1- As a Deacon Advisor for 5-years: That time covered my eldest sons’ first priesthood experiences. From this Sterling was given great examples by his eldest brothers. He too was handsome in a white shirt and tie, before the untucked shirts, sagging pants & fresh out-of-bed-head look began to take over his generation. When playing basketball on our front yard Blazer court, I laughed when his pants dropped to his knees. Three cheers for spandex! Of course, I took the opportunity to score on him. LOL. He’d roast me with the ‘white men can’t jump,” routine. In defense I’d throw the disability & age card, only to get it thrown back at me declaring I’m actually “Creped & Ancient—over half a century to boot!”  
                #2- Our family is the greatest ‘Whiffle-Ball Team in the World:’ No neighbor family, group of friends or LDS family could beat the 10-of us! When the twins were 3 to 7 years old they were great Whiffle-Ball players, helping us win several games. What a blast! 
                #3- T-ball: My #2 & #3 hitters, were Sterr & Starr. They were as effective as their older siblings, ‘Casey the sand-lot slugger, Heith, Sena & Jeremy my line-drive hitters in their hey-day. Sterling hated not getting to hit more than once in an innings rotation. His next chance he made it count, blasting a home run grunting like me. Both twins grunted when hitting the ball, like Dad! I couldn’t have been more proud. We never lost a T-ball game over 6-years. Kids keep score! Winning makes the game fun, & outs makes the game real. Life is about winning and losing honorably. Get over it Portlandian-snowflakes! Then came Coach-Pitch & I threw faster than any coach, suited to players capacity. Sterling caught on fast, his capacity loomed large. Sterling never wanted me to throw underhand or slow down. We never lost any of those games, ready for the next level: Minor Little League, but without me coaching they moved on to other activities.   
                #4- Talents: In Highs School, Sterling could pitch 75-mph with a mean curve. He was very good on his skateboard & BMX bike. Once he had to show me a flip on his bike at the Tigard Skate Park bowl & he scared me good. His head scraped the metal edge of the bowl when upside down. I wouldn’t watch another flip until he put on his helmet. Then I’d watch entire routines setting him apart. Water Polo, was a growing talent. If he didn’t foul as much he’d have stayed in the pool more. But, boy could he dish it back to radical foes in both shallow & the deep end!  
                #5- Firestarter: As an impatient 3-year old boy, living in Olalla WA, Sterling was upset he couldn’t start a fire on his own with his older brothers in the wooded backyard. So he started a fire in his room that night using the stuffing from his pillow. He got it going along with the fire alarms. Thereafter, he never had a problem starting scout campfires in any weather.
                #6- School Chalkboard climbing: He was known to follow in the footsteps of his elder brother Jeremy, able to climb all around any class room at 7-years old, without touching the floor. No chalk board could stop them. He was also known for scaling school roofs, turning on school and park sprinklers and helping elder siblings put missionary bikes on our roof.  
                #7- Small motor engines: Sterling taught himself how to fix small motor engines & repair many things. True Jack of all Trades. He made me proud following in the footsteps of his siblings, each with a great work ethic. Boy could he tear shingles off a roof fast! 
                #8- Building stuff with Sterling: Loved it. He wasn’t around much the last 2-years, but enough to help with repairs & upgrades to our former Tigard home, enabling us to sell fast. I thank him for all his help around the house when his sibling left home or busy. He stepped up when mom was very sick & I was down with back surgeries. He always got after me (like all my kids) when I was over-doing things. He was quick to carry the heavy stuff & fix the difficult things, pushing me aside. I just had to be a part of projects with them all and cope the consequences later. Not the greatest example, I know. I likewise rejoiced building one last project with his elder brothers Casey & Jeremy before they went off to WAR. Only Sterling didn’t return safely from his war zone after our last roofing project. His building interests began as a Cub Scout building cool soap-box cars. Like all my boys, he insisted his dad wouldn’t build his soap box car for him, like some dads. I did get to teach him the use of arrow dynamics, weights, gravity & graphite, & he took it over the top.  
                #9- Sterling & Shanelle were like Batman & Robin. Starr generally came to Sterling’s rescue verbally, whereas Sterling was a more hands on guy. If someone was bullying Starr, he’d come running out of nowhere plowing them over. Into teen hood Sterr watched Starr hold her own, prepared to pounce in his way if necessary. 
                #10- Comedy: Joking was Sterling’s mechanism to cope his many life trials. Boy did he have some whoppers! We couldn’t help busting up laughing at his jokes skirting the PG-13 line. Hum, again ‘my bad example.’ Perhaps his friends may share a Sterling special: G or PG-13 sample? Topping it off was his infectious laugh, one of a kind. 
                #11- Sterling reminds me of the little boy on U-Tube: “Linda, Linda, listen, listen Linda…, His Mom replied: “Why you call me Linda?” At eight, Sterling said as much: “Mama, Mama listen, Starr has put her finger in the light socket again. Her hair is a hot mess (2-foot afro). Mama, come look, listen, listen mama, hurry, ‘Stuck-Electric’ is blowing her top!” 
                #12- Sterling’s Dad says this last memory is to be from me: I’ll share this one:???
                I relish the thought of seeing my son again, perfectly healthy. It grounds me, although the entire family misses him terribly; especially the good, loving, helpful, strong, smart, funny and spiritually dutiful son he was more often than not. I have always forgiven him for his mighty vitality- and wayward mix of things, some costly, some sweet, some bitter, hot & spicy: THAT’S MY STER-FRY! Reminds me when Sterling’s hungry, ever copying me… “Dad, you love me?” “Of course Son!” and he’d say, “Feed my Sheep!” A Sunday School lesson he knows well—even as a lost lamb; often found, waiting his potential. We now hope he waits the opportunity to advance through temple work & be numbered among the Good Shepherds fold.      
                However bias, these words of Mama Rings true today: “Sterling is still my baby boy, he can be a good boy, loving & handsome. He’s a mama’s boy.” Our hope & faith is about reuniting into eternity as an eternal family, overcoming the prophetic words in Cyndi’s Patriarchal Blessing—conveying she’d have, many blessing & many losses.” 
                To honor my son, is to not get angry, drunk, or high, blame or contend with anyone, but remember the good times—stories we all have of him on a regular basis. If I can cool my jets about the circumstances of his death, anyone can. Then again I’m 800-miles away. Just don’t cross the beast; Sterling’s eldest brother Casey. The tough love drill Sargent type in Sterr’s life—offsetting family’s blind-enabling. I’m glad to see he’s there for his little brother, securing a safe funeral accommodations (thank you bishop) & ensuring the processing of his remains are respectful with proper identification, beyond DNA & FBI finger prints, unable to see him one last time. So we will remember him as we saw him last: Vibrant and happy, knowing his spirit yet lives and thriving fully healthy! Ooorah! 
                As Mama would tell her baby boy all his life: “I love you from the tips of your toes to the tip of the moon…” He’d respond like all our kids/grand-kids, “I love you more…, “NO, I love you more,” Mom would reply, & on & on it went like, ‘The Never-Ending Story.’ God bless you Son. I’LL NEVER FORGET YOU, you’re too special, even if you recently lost sight of that. PS: Check in on Mom, Starr & your nephew Zachiah as you can, Ok? He’d likely feel your spirit presence before any of us, beaming with your smile! Thanks, little buddy. See you soon! In the name of Jesus Christ, Amen!    
                A word about Sterling, from Shanelle—Sterling twin sister: TBA</p>
                <p></p>
                <p></p>
            </div>
            </div>
            </div>
        </div>
    )
}

export default Sterling;